FROM node:20-alpine

# Set the working directory
WORKDIR /app/frontend

# Copy package.json and package-lock.json
# COPY package.json package-lock.json ./
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the application
CMD ["npm", "run", "build"]