version: "3.8"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        environment:
            - CHOKIDAR_USEPOLLING=true
            - VITE_BACKEND_HOST=backend
            - VITE_BACKEND_PORT=81
            - VITE_LIVESERVER_HOST=live-server
            - VITE_APP_URL=http://localhost
        volumes:
            - ./frontend:/app/frontend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        depends_on:
            - database
            - elasticsearch
        environment:
            - DB_HOST=database
            - ELASTICSEARCH_HOST=elasticsearch
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/var/www/html

    live-server:
        build:
            context: ./live-server
            dockerfile: Dockerfile
        depends_on:
            - database
        environment:
            - DB_HOST=database
        volumes:
            - ./live-server:/app/live-server

    database:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: gr3
            MYSQL_USER: root
            MYSQL_PASSWORD:
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./database:/var/lib/mysql

    nginx:
        image: nginx:alpine
        depends_on:
            - backend
            - frontend
        ports:
            - "8000:81"
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./backend:/var/www/html
            - ./frontend/dist:/usr/share/nginx/html

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        environment:
            - xpack.security.enabled=false
            - "discovery.type=single-node"
        ports:
            - 9200:9200
        volumes:
            - ./elasticsearch_data:/usr/share/elasticsearch/data

volumes:
    database:
        driver: local
    elasticsearch_data:
        driver: local

networks:
    default:
        name: gr3-app
