version: "3.8"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                - VITE_APP_URL=http://localhost
                - VITE_BACKEND_HOST=localhost
                - VITE_LIVESERVER_HOST=localhost
        restart: "always"
        container_name: frontend
        environment:
            - VITE_APP_URL=http://localhost
            - VITE_BACKEND_HOST=localhost
        ports:
            - "80:80"

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        depends_on:
            - database
            - elasticsearch
        environment:
            - DB_HOST=database
            - DB_USER=vutuankiet
            - DB_PASSWORD=mysql12345
            - ELASTICSEARCH_HOST=elasticsearch
            - APP_URL=http://localhost:8000
            - FRONTEND_URL=http://localhost/
        restart: always
        volumes:
            - ./backend:/var/www/html

    live-server:
        build:
            context: ./live-server
            dockerfile: Dockerfile
        restart: always
        container_name: live-server
        depends_on:
            - database
        environment:
            - NODE_ENV=production
            - DB_HOST=database
            - DB_USER=vutuankiet
            - DB_PASSWORD=mysql12345
        ports:
            - "3000:3000"

    nginx:
        image: nginx:alpine
        restart: always
        container_name: nginx
        depends_on:
            - backend
        ports:
            - "8000:81"
        volumes:
            - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./backend:/var/www/html

    database:
        image: mysql:8.0
        container_name: database
        environment:
            MYSQL_DATABASE: gr3
            MYSQL_ROOT_PASSWORD: mysql12345
            MYSQL_USER: vutuankiet
            MYSQL_PASSWORD: mysql12345
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./database:/var/lib/mysql

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        restart: always
        environment:
            - xpack.security.enabled=false
            - "discovery.type=single-node"
        ports:
            - 9200:9200
        volumes:
            - ./elasticsearch_data:/usr/share/elasticsearch/data
