version: "3.8"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                - VITE_APP_URL=http://localhost
                - VITE_BACKEND_HOST=localhost
                - VITE_LIVESERVER_HOST=localhost
        restart: "always"
        environment:
            - VITE_APP_URL=http://localhost
            - VITE_BACKEND_HOST=backend
        ports:
            - "80:80"
        # volumes:
        #     - ./frontend:/app/frontend
        #     - /app/frontend/node_modules/

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        depends_on:
            - database
            - elasticsearch
        environment:
            - DB_HOST=database
            - DB_PASSWORD=root
            - ELASTICSEARCH_HOST=elasticsearch
        restart: always
        ports:
            - "8000:8000"
    #     # volumes:
    #     #     - ./backend:/var/www/html

    live-server:
        build:
            context: ./live-server
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - database
        environment:
            - DB_HOST=database
        ports:
            - "3000:3000"
    #     # volumes:
    #     #     - ./live-server:/app/live-server
    #     #     - /app/live-server/node_modules/

    database:
        image: mysql:8.0
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: gr3
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./database:/var/lib/mysql

    # # nginx:
    # #     image: nginx:alpine
    # #     restart: always
    # #     depends_on:
    # #         - backend
    # #         - frontend
    # #     ports:
    # #         - "81:81"
    # #         - "80:80"
    # #     volumes:
    # #         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    # #         - ./backend:/var/www/html
    # #         - ./frontend/dist:/usr/share/nginx/html

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        restart: always
        environment:
            - xpack.security.enabled=false
            - "discovery.type=single-node"
        ports:
            - 9200:9200
        volumes:
            - ./elasticsearch_data:/usr/share/elasticsearch/data
